[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
tokio = { version = "1.40.0", features = ["full"] }
byteorder = "1.5.0"
lazy_static = "1.5.0"
tokio-console = "0.1.12"